language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "stable"

sudo: false

notifications:
  email: false

install:
  - yarn add global codecov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn prepare
  - yarn lint
  - yarn test:ci

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
